@host = urlshortnercap.azurewebsites.net
//@host = http://localhost:5160
# API: Get short url
# This call should retrun a string "http://localhost:5160/navigate/ge123"
# API: Get short url
GET {{host}}/shortUrls/urlId1
Accept: application/json
Authorization: Basic email1@gmail.com:p1a1s1s1w1o1r1d

###

# API: list all urls
GET {{host}}/shortUrls
Accept: application/json
Authorization: Basic email1@gmail.com:p1a1s1s1w1o1r1d

###

# API: Create or update short url
PUT {{host}}/shortUrls/urlId7
Accept: application/json
Content-Type: application/json
Authorization: Basic email1@gmail.com:p1a1s1s1w1o1r1d

{
    "url": "http://www.facebook.com/"
}

###

# API: delete short url
DELETE {{host}}/shortUrls/urlId7
Accept: application/json
Authorization: Basic email1@gmail.com:p1a1s1s1w1o1r1d

###

# # API: Get number of hits
# GET {{host}}/shortUrls/urlId1/hits
# Accept: application/json

###
# API: navigate to shortUrl
GET {{host}}/navigate/urlId3
Accept: application/json
Authorization: Basic email1@gmail.com:p1a1s1s1w1o1r1d